version: "3.3"

services:
  db:
   image: postgres:14.1-alpine
   container_name: postgres
   restart: always
   tty: true
   volumes:
     - ../.pgdata:/var/lib/postgresql/data
   environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=secret
     - POSTGRES_DB=distributed-system
   ports:
     - 0.0.0.0:5432:5432

volumes:
  .pgdata:
    driver: local