version: "3.3"

services:
  db:
   image: postgres:14.1-alpine
   container_name: postgres
   restart: always
   tty: true
   volumes:
     - ../.pgdata:/var/lib/postgresql/data
   environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=secret
     - POSTGRES_DB=distributed-system
   ports:
     - 0.0.0.0:5432:5432
  zookeeper:
    platform: linux/x86_64
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  kafka:
    platform: linux/x86_64
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    ports:
      - "29092:29092"
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
  kafkaui:
    platform: linux/x86_64
    container_name: kafkaui
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:9092"
      KAFKA_CLUSTERS_0_NAME: "KAFKA LOCAL"
      KAFKA_CLUSTERS_0_ZOOKEEPER: "zookeeper:2181"
  web:
    platform: linux/x86_64
    container_name: web
    build: .
    depends_on:
      - kafka
      - db
    environment:
      - POSTGRES_HOST=postgres://postgres:secret@db:5432/distributed-system?sslmode=disable
      - HOST=0.0.0.0
      - PORT=5000
      - KAFKA_HOST=kafka
      - KAFKA_PORT=29092
    command: swag init && go build . && ./distributed-system-go server
    ports:
      - "0.0.0.0:5000:5000"
    volumes:
      -  .:/go/src/app
  validate-balance-worker:
    platform: linux/x86_64
    container_name: validate-balance-worker
    image: golang:1.18
    depends_on:
      - kafka
    environment:
      - KAFKA_HOST=kafka
      - KAFKA_PORT=29092
    volumes:
      -  .:/go/src/app
    working_dir: /go/src/app
    command: go run . validate-balance-worker
  validate-user-status-worker:
    platform: linux/x86_64
    container_name: validate-user-status-worker
    image: golang:1.18
    depends_on:
      - kafka
    environment:
      - KAFKA_HOST=kafka
      - KAFKA_PORT=29092
    volumes:
      -  .:/go/src/app
    working_dir: /go/src/app
    command: go run . validate-user-status-worker
volumes:
  .pgdata:
    driver: local